version: '3.7'

services:
    nginx:
      image: nginx:alpine
      restart: on-failure
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
    todo:
      image: nvrbckdown/todo-app:latest
      restart: always
      